{% set name = "pythonvirgotools" %}
{% set version = "5.1.5" %}

package:
   name: "{{ name }}"
   version: "{{ version }}"

source:
   url: http://software.igwn.org/lscsoft/source/{{ name }}-{{ version }}.tar.gz
   sha256: eb64bb89de309f25922d1b454f56c728315de335ccd1bcb0763565f89f622ff8

build:
  number: 2
  noarch: python
  script: {{ PYTHON }} -m pip install . -vvv

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
  run:
    - python >={{ python_min }}
    - pyfd
    - pycm
    - future
    - numpy
    - pytz
    - tzlocal <=2.1

test:
  requires:
    - python {{ python_min }}
  imports:
    - virgotools

about:
  home: "https://git.ligo.org/virgo/virgoapp/PythonVirgoTools"
  license: "GPL-2.0-or-later"
  license_family: "GPL"
  license_file: "LICENSE"
  summary:
    PythonVirgoTools is a collection of Python functions for interacting 
    with the software, hardware and data of the Virgo Interferometer. 
    These functions were mainly written for daily use in the control room, 
    but some of these might also be useful for e.g. DetChar work.

extra:
  recipe-maintainers:
      - rhyspoulton
      - fcarbogn 
